{% if cookiecutter.enforce_conventional_commits -%}
default_install_hook_types:
  - commit-msg
  - pre-commit
{% endif -%}
repos:
  - repo: https://e.coding.net/xinxiangsui/github-mirrors/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://e.coding.net/xinxiangsui/github-mirrors/poetry.git
    rev: 2.0.1
    hooks:
      - id: poetry-check
  - repo: https://e.coding.net/xinxiangsui/github-mirrors/ruff-pre-commit.git
    rev: v0.9.5
    hooks:
      - id: ruff
        args:
          - '--fix'
      - id: ruff-format
